server/app/__init__.py
# -*- coding: utf-8 -*-
from flask import Flask
import config

from flask_babel import Babel
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_moment import Moment
from flask_session import Session
from flask_sqlalchemy import SQLAlchemy
from flask_talisman import Talisman
from flask_wtf.csrf import CSRFProtect
from redis import StrictRedis
from werkzeug.contrib.fixers import ProxyFix


session = Session()
bootstrap = Bootstrap()
moment = Moment()
babel = Babel()
login_manager = LoginManager()
csrf = CSRFProtect()
talisman = Talisman()
db = SQLAlchemy()
migrate = Migrate()


def create_app(cfg=config):
    app = Flask(__name__)
    app.config.from_object(cfg)
    app.wsgi_app = ProxyFix(app.wsgi_app)

    cfg = app.config
    csp = cfg['CSP']
    cache_redis = StrictRedis(
        host=cfg['REDIS_CACHE_HOSTNAME'],
        port=cfg['REDIS_CACHE_PORT'])

    cfg.update(CACHE_REDIS=cache_redis)
    cfg.update(SESSION_REDIS=cache_redis)

    session.init_app(app)
    bootstrap.init_app(app)
    moment.init_app(app)
    babel.init_app(app)
    login_manager.init_app(app)
    csrf.init_app(app)
    talisman.init_app(app, content_security_policy=csp)
    db.init_app(app)
    migrate.init_app(app, db)

    app.redis_cache = cache_redis

    from app.wide import bp as bp_wide
    from app.wide import filters
    from app.main import bp as bp_main
    from app.auth import bp as bp_auth

    app.register_blueprint(bp_wide)
    app.register_blueprint(bp_main)
    app.register_blueprint(bp_auth)

    app.jinja_env.filters['map_obj_true'] = filters.map_obj_true
    app.jinja_env.filters['str_3dots'] = filters.str_3dots
    app.jinja_env.filters['uppercase_first_letter'] = filters.uppercase_phrase
    app.jinja_env.filters['last_char_dot'] = filters.last_char_dot
    app.jinja_env.filters['format_timestamp'] = filters.format_timestamp
    app.jinja_env.filters['hide_string'] = filters.hide_string
    app.jinja_env.filters['first_word'] = filters.first_word
    app.jinja_env.filters['first_char'] = filters.first_char
    app.jinja_env.filters['to_date_humanize'] = filters.to_date_humanize
    app.jinja_env.globals['url_for_other_page'] = filters.url_for_other_page

    return app

server/app/main/__init__.py
# -*- coding: utf-8 -*-
from flask import Blueprint


bp = Blueprint('main', __name__)


from app.main import routes

server/app/main/routes.py
# -*- coding: utf-8 -*-
from app.main import bp
from flask import render_template

@bp.route('/ping', methods=['GET'])
def ping():
    return 'pong'


@bp.route('/', methods=['GET'])
def landing():
    return '0'

from os import listdir

@bp.route('/frequencies', methods=['GET'])
def frequencies():
    title = 'Frecuencies 1 & 2 '
    with open('app/main/frequencies.txt') as f:
        lines = f.read()

    frec_seen = []
    x = 0
    rep_frec = []
    i = 0
    while i < 2:
        for line in lines.splitlines():
            x = x + int(line)
            if x in frec_seen:
                rep_frec.append(x)

            frec_seen.append(x)
        i += 1
    if len(rep_frec) != 0:
        rep_frec = rep_frec[0]
    else:
        rep_frec = 'None'



    return render_template('ini.html', fr=x/2, rep=rep_frec, title=title)

server/app/wide/__init__.py
# -*- coding: utf-8 -*-
from flask import Blueprint


bp = Blueprint('wide', __name__)


from app.wide import routes

server/app/wide/routes.py
# -*- coding: utf-8 -*-
from flask import current_app
from flask import has_request_context
from flask import request
from flask import session as fsession
from app import babel

from app.wide import bp


@babel.localeselector
def get_locale():
    langs_available = current_app.config['LANGUAGES']

    if has_request_context():
        # Return lang from browser with request context
        browser = request.accept_languages.best_match(langs_available)
        find_lng = False
        for l in langs_available:
            if browser == l:
                find_lng = True
                break
        if find_lng is False:
            browser = current_app.config['BABEL_DEFAULT_LOCALE']
        return fsession.get('lang', browser)

    # mainly use for test purpose
    with current_app.test_request_context():
        browser = request.accept_languages.best_match(langs_available)
        find_lng = False
        for l in langs_available:
            if browser == l:
                find_lng = True
                break
        if find_lng is False:
            browser = current_app.config['BABEL_DEFAULT_LOCALE']
        return fsession.get('lang', browser)


@babel.timezoneselector
def get_timezone():
    if has_request_context():
        tz = fsession.get('tz', None)
        return tz

    # mainly use for test purpose
    with current_app.test_request_context():
        tz = fsession.get('tz', None)
        return tz

server/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
   <div
    <a href =" {{ url_for('main.landing') }}" >   home <a>
    <a href =" {{ url_for('main.ping') }} ">   ping  <a>
    <a href =" {{ url_for('main.frequencies') }} ">   Frequencies <a>
    <a href=" {{ url_for('auth.register') }}">   Register</a>
    <a href=" {{ url_for('auth.login') }}">   Login</a>
   </div>
    {% block content %} 
    {% endblock %}

</body>
</html>

server/app/templates/frequencie_1.html
{% extends 'base.html' %}
{% block content %}
<h4>Frequencie 1</h4>

Total: {{ fr }}
{% endblock %}

server/app/templates/ini.html
{% extends 'base.html' %}
{% block content %}
<h4>{{ title }} </h4>

Frecuencies Total: {{ fr }}

Frequencies part 2 : {{ rep }}
{% endblock %}

server/app/templates/macro.html
{% macro render_field(field) %}
        <td> {{ field.label }} </td>
        <dd> {{ field(**kwargs)|safe}}</dd>
    {% if field.errors %}
        <ul>
            {% for error in fields.errors %}
                <li> {{ error }} </li>
            {% endfor %}
        </ul>
    {% endif %}
        
{% endmacro %}

server/app/templates/register.html
{% extends 'base.html' %}
{% block content %}
<h4>{{ title }}</h4>
<li>{{ message }}</li>
{% from "macro.html" import render_field %}
    <form method="post">
    {{ form.hidden_tag() }}
    {{ render_field(form.username) }}
    {{ render_field(form.password) }}
    {{ form.submit() }}
    </form>

{% endblock %}